/** Rotas conhecidas do portal (outcome → href). */
export const MENU_OUTCOME_PATHS: Record<string, string> = {
  "/painel": "/painel",
  "/nfe/emissao": "/nfe/emissao",
  "/nfe/notas-emitidas": "/nfe/notas-emitidas",
  "/nfe/eventos-fiscais": "/nfe/eventos-fiscais",
  "/nfse/emissao": "/nfse/emissao",
  "/nfse/mensais": "/nfse/mensais",
  "/nfse/emitidas": "/nfse/emitidas",
  "/cadastros/pessoas": "/cadastros/pessoas",
  "/cadastros/produtos": "/cadastros/produtos",
  "/cadastros/veiculos": "/cadastros/veiculos",
  "/cadastros/usuarios": "/cadastros/usuarios",
  "/cadastros/empresa": "/cadastros/empresa",
  "/tributacao/nfse-servico": "/tributacao/nfse-servico",
  "/tributacao/grupo-tributario": "/tributacao/grupo-tributario",
  "/tributacao/operacao-fiscal": "/tributacao/operacao-fiscal",
  "/tributacao/configura-of-gt": "/tributacao/configura-of-gt",
  "/conta/integracao": "/conta/integracao",
  "/conta/contabilidade": "/conta/contabilidade",
  "/conta/assinatura": "/conta/assinatura",
  "/conta/lgpd": "/conta/lgpd",
  "/conta/auditoria": "/conta/auditoria",
  "/conta/metricas": "/conta/metricas",
  "/parametros/configurar-menu": "/parametros/configurar-menu",
  "/parametros/permissoes": "/parametros/permissoes",
};

export const MENU_LABEL_PATHS: Record<string, string> = {
  início: "/painel",
  inicio: "/painel",
  "emitir nf-e": "/nfe/emissao",
  "nf-e — xmls / danfe": "/nfe/notas-emitidas",
  "eventos da nf-e": "/nfe/eventos-fiscais",
  "emitir nfs-e": "/nfse/emissao",
  "nfs-e mensais": "/nfse/mensais",
  "nfs-e emitidas": "/nfse/emitidas",
  clientes: "/cadastros/pessoas",
  produtos: "/cadastros/produtos",
  veículos: "/cadastros/veiculos",
  veiculos: "/cadastros/veiculos",
  usuários: "/cadastros/usuarios",
  usuarios: "/cadastros/usuarios",
  emitentes: "/cadastros/empresa",
  "configurar menu": "/parametros/configurar-menu",
  permissões: "/parametros/permissoes",
  permissoes: "/parametros/permissoes",
};
