-- Modelos de NFS-e para reemissão mensal (clonar competência)
CREATE TABLE nfse_operacao_mensal (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    nome VARCHAR(120) NOT NULL,
    tomador_cnpj VARCHAR(14) NOT NULL,
    tomador_razao VARCHAR(255) NOT NULL,
    tomador_email VARCHAR(255) NULL,
    tomador_telefone VARCHAR(30) NULL,
    cep VARCHAR(8) NULL,
    logradouro VARCHAR(255) NULL,
    numero VARCHAR(20) NULL,
    complemento VARCHAR(100) NULL,
    bairro VARCHAR(120) NULL,
    cidade VARCHAR(120) NULL,
    uf VARCHAR(2) NULL,
    codigo_municipio_ibge VARCHAR(7) NULL,
    valor_servicos DECIMAL(15, 2) NOT NULL,
    descricao_servico VARCHAR(2000) NOT NULL,
    item_lista_servico VARCHAR(15) NOT NULL,
    nbs VARCHAR(9) NULL,
    cnae VARCHAR(7) NULL,
    municipio_prestacao_ibge VARCHAR(7) NULL,
    aliquota_iss DECIMAL(7, 4) NULL,
    tributacao_issqn VARCHAR(1) NOT NULL DEFAULT '1',
    iss_retido VARCHAR(1) NOT NULL DEFAULT '1',
    simples_nacional VARCHAR(1) NOT NULL DEFAULT '1',
    regime_especial VARCHAR(1) NOT NULL DEFAULT '0',
    serie_rps VARCHAR(5) NOT NULL DEFAULT '1',
    observacoes VARCHAR(1000) NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    ultima_emissao_chave VARCHAR(50) NULL,
    ultima_emissao_em TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_nfse_op_mensal_empresa FOREIGN KEY (empresa_id) REFERENCES empresa (id) ON DELETE CASCADE,
    CONSTRAINT uk_nfse_op_mensal_empresa_nome UNIQUE (empresa_id, nome)
);

CREATE INDEX idx_nfse_op_mensal_empresa ON nfse_operacao_mensal (empresa_id, ativo);
