spring:
  datasource:
    url: jdbc:mysql://localhost:3307/nfse_portal?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: nfse
    password: nfse
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
